### ISSUE TITLE
failed to open video device: Device or resource busy

### ISSUE THREAD

**Issue by skybert** [floe/backscrub#115]
Hi there,

first off, thanks for a great project. This is the only thing I'm missing from using Teams (web) on Linux.

However, I cannot get it to work together with Chrome/Teams, I hope you can help me.

## Teams first
If I start a Team meeting first, then `backscrub`, I get:
```
$ ./build/backscrub -d -d -b ~/pictures/wallpapers/foo.jpg -c /dev/video0 -v /dev/video10
..
failed to open video device: Device or resource busy
``` 

## backscrub first
If I start `backscrub` first with the above command, I can see myself with the wallpaper working, but Chrome/Teams cannot open the video device ("Video not working")

## Versions
- Debian GNU/Linux 11 (bullseye)
- Kernel `5.10.0-8-amd64`
- Xorg `1.20.11`
- tensorflow at `a4dfb8d1a71`
- backscrub at `b264847f59a983b0884b5d61bbe27864b6218b8e`

**Comment by BenBE** [comment]
The first behavior is expected as Teams opens the video device and thus locks it from backscrub.

The second case is similar except its in reverse here with backscrub locking the device and Teams trying to access it too.

The second case should be resolved though when you ask Teams to use `/dev/video10` (the virtual output) instead of `/dev/video0` (your webcam input) instead. This should be available in the video settings dialog. But since I'm not using Teams I can't tell you about the specifics where the exact setting is located.

**Comment by skybert** [comment]
Thanks for your explanation, @BenBE. It makes perfect sense. I've got it working now 👍
